eureka:
    client:
        register-with-eureka: true  # register this service on eureka server
        fetch-registry: true
        service-url:
             defaultZone: http://localhost:8761/eureka/   #port no of eureka server
    instance:
              hostname: localhost   
           
