server:
    port: 8761  #default port
spring:
    application:
           name: eureka-server
           

eureka:
  client:
    register-with-eureka: false  #server resister on server ,no requeire so write false
    fetch-registry: false 
